### ISSUE TITLE
rank guid not set in classification

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/bie-index#149]
Orignally reported to the NSL:

http://bie.ala.org.au/ws/species/http://id.biodiversity.org.au/node/apni/7845073 does not have genusGuid set in the classification. Similarly, if you go up one level, http://bie.ala.org.au/ws/species/http://id.biodiversity.org.au/node/apni/8807273 does not have familyGuid set.

```
{
  "taxonConcept": {
    "guid": "http://id.biodiversity.org.au/node/apni/8807273",
    "parentGuid": "http://id.biodiversity.org.au/node/apni/8807368",
    "nameString": "Rubiaceae",
    "nameComplete": "Rubiaceae Juss.",
    "nameFormatted": "<span class=\"scientific-name rank-family\"><span class=\"name\">Rubiaceae</span> <span class=\"author\">Juss.</span></span>",
    "author": "Juss.",
    "taxonomicStatus": "accepted",
    "nomenclaturalStatus": "nom. cons.",
    "rankString": "family",
    "nameAuthority": "Australian Plant Census",
    "rankID": 5000,
    "namePublishedIn": "Jussieu, A.L. de (1789), Genera Plantarum",
    "namePublishedInYear": "1789",
    "namePublishedInID": null,
    "infoSourceURL": "http://id.biodiversity.org.au/node/apni/8807273",
    "datasetURL": "http://collections.ala.org.au/public/show/dr5214",
    "scientificNameID": "http://id.biodiversity.org.au/name/apni/54575"
  },
  "taxonName": [],
  "classification": {
    "family": "Rubiaceae",
    "familyGuid": null,
    "class": "Equisetopsida",
    "kingdom": "Plantae",
    "order": "Gentianales",
    "phylum": "Charophyta",
    "subclass": "Magnoliidae",
    "superorder": "Asteranae",
    "classGuid": "http://id.biodiversity.org.au/node/apni/8807565",
    "kingdomGuid": "http://id.biodiversity.org.au/node/apni/8807563",
    "orderGuid": "http://id.biodiversity.org.au/node/apni/8807368",
    "phylumGuid": "http://id.biodiversity.org.au/node/apni/8807562",
    "subclassGuid": "http://id.biodiversity.org.au/node/apni/8807566",
    "superorderGuid": "http://id.biodiversity.org.au/node/apni/8807370",
    "scientificName": "Rubiaceae"
  },
  ...
'''

**Comment by charvolant** [comment]
Fixed by classification map fix in https://github.com/AtlasOfLivingAustralia/bie-index/issues/151

**Comment by jhpoelen** [comment]
@charvolant - was just checking my ignored integration tests . . . and noticed that this issue is not yet resolved. You mentioned that is was fixed by #151 . Does this mean that the fix is in place, but has not yet been released into production?

**Comment by adam-collins** [comment]
Appears working in the current index.
