### ISSUE TITLE
Bulk lookup matches hybrid rather than species

### ISSUE THREAD

**Issue by raymondben** [AtlasOfLivingAustralia/bie-index#75]
Searching for "Melaleuca fluviatilis" returns a match to Melaleuca fluviatilis x M.nervosa, despite Melaleuca fluviatilis [existing in ALA](http://bie.ala.org.au/species/http://id.biodiversity.org.au/node/apni/2915874#overview).

See https://github.com/AtlasOfLivingAustralia/ALA4R/issues/19

**Comment by nickdos** [comment]
Please confirm which service this is hitting.

**Comment by raymondben** [comment]
Sorry: http://bie.ala.org.au/ws/species/lookup/bulk

**Comment by nickdos** [comment]
I've deployed a major change for this issue - I've tried to support the fields that were being used in the old API, so If you've updated code for the "new' version, then you might need to revert them back to what they were in the older stable version (if that makes sense).

here is the output for `{"names":["Melaleuca fluviatilis","red kangaroo"]}`:

```
[{
    "identifier": "http://id.biodiversity.org.au/node/apni/2915874",
    "guid": "http://id.biodiversity.org.au/node/apni/2915874",
    "parentGuid": "http://id.biodiversity.org.au/node/apni/3676360",
    "name": "Melaleuca fluviatilis",
    "nameComplete": "Melaleuca fluviatilis Barlow",
    "commonName": null,
    "commonNameSingle": null,
    "rank": "species",
    "rankId": 7000,
    "acceptedConceptGuid": "http://id.biodiversity.org.au/node/apni/2915874",
    "acceptedConceptName": "Melaleuca fluviatilis",
    "taxonomicStatus": "accepted",
    "imageId": null,
    "imageUrl": "",
    "thumbnailUrl": "",
    "largeImageUrl": "",
    "smallImageUrl": "",
    "imageMetadataUrl": "",
    "kingdom": "Plantae",
    "phylum": "Charophyta",
    "classs": "Equisetopsida",
    "order": "Myrtales",
    "family": "Myrtaceae",
    "genus": "Melaleuca",
    "author": "Barlow",
    "linkIdentifier": null
}, {
    "identifier": "urn:lsid:biodiversity.org.au:afd.taxon:31a9b8b8-4e8f-4343-a15f-2ed24e0bf1ae",
    "guid": "urn:lsid:biodiversity.org.au:afd.taxon:31a9b8b8-4e8f-4343-a15f-2ed24e0bf1ae",
    "parentGuid": "urn:lsid:biodiversity.org.au:afd.taxon:9e6a0bba-de5b-4465-8544-aa8fe3943fab",
    "name": "Macropus rufus",
    "nameComplete": "Macropus rufus (Desmarest, 1822)",
    "commonName": ["Red Kangaroo"],
    "commonNameSingle": "Red Kangaroo",
    "rank": "species",
    "rankId": 7000,
    "acceptedConceptGuid": "urn:lsid:biodiversity.org.au:afd.taxon:31a9b8b8-4e8f-4343-a15f-2ed24e0bf1ae",
    "acceptedConceptName": "Macropus rufus",
    "taxonomicStatus": "accepted",
    "imageId": "0cb7bd35-b558-4596-83d1-8ffe54b27f93",
    "imageUrl": "http://images.ala.org.au/image/proxyImage?imageId=0cb7bd35-b558-4596-83d1-8ffe54b27f93",
    "thumbnailUrl": "http://images.ala.org.au/image/proxyImageThumbnail?imageId=0cb7bd35-b558-4596-83d1-8ffe54b27f93",
    "largeImageUrl": "http://images.ala.org.au/image/proxyImageThumbnailLarge?imageId=0cb7bd35-b558-4596-83d1-8ffe54b27f93",
    "smallImageUrl": "http://images.ala.org.au/image/proxyImageThumbnailLarge?imageId=0cb7bd35-b558-4596-83d1-8ffe54b27f93",
    "imageMetadataUrl": "http://images.ala.org.au/ws/image/0cb7bd35-b558-4596-83d1-8ffe54b27f93",
    "kingdom": "ANIMALIA",
    "phylum": "CHORDATA",
    "classs": "MAMMALIA",
    "order": "DIPROTODONTIA",
    "family": "MACROPODIDAE",
    "genus": "Macropus",
    "author": "(Desmarest, 1822)",
    "linkIdentifier": null
}]
```

**Comment by raymondben** [comment]
Thanks Nick - that seems to resolve the issue of matching on subspecies or hybrids in preference to the species itself. I can still see some other odd name searching results, but I'll PM you those rather than add them here; I don't think they are necessarily stemming from the same underlying issue.
